### PR TITLE
Views

### PR DESCRIPTION
**Pull request by RWUBAKWANAYO**
## Description
In this pull request I :
- Added the Views associated with the Models and Controllers.
- Implemented the design from the sneak peek wireframes.

## General requirements
- [x] There are no linter errors.
- [x] Followed the Github flow.
- [x] The documentation is professional.

## Ruby requirements
- [x] Followed [best practices of Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md)
## Project requirements
[Link to the project speifications](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)

## Project running in the browser screenshot

Screenshot (385)

Screenshot (386)

Screenshot (387)

Screenshot (388)

**N.B: For the reason of how we modified our models by adding validations, previously. we have to add `posts_counter`, `comments_counter`, `likes_counter` once we create a new `user`, `post`**
***
## Example I used to generate data:
```ruby
first_user = User.create(name: 'Tom', photo: 'https://freepngimg.com/thumb/man/22654-6-man-thumb.png', bio: 'Teacher from Mexico.',posts_counter:0)
second_user = User.create(name: 'Lilly', photo: 'https://freepngimg.com/thumb/man/22654-6-man-thumb.png', bio: 'Teacher from Poland.',posts_counter:0)

first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post', comments_counter: 0, likes_counter: 0)
second_post = Post.create(author: first_user, title: 'Hello', text: 'This is my second post', comments_counter: 0, likes_counter: 0)
third_post = Post.create(author: first_user, title: 'Hello', text: 'This is my third post', comments_counter: 0, likes_counter: 0)
fourth_post = Post.create(author: first_user, title: 'Hello', text: 'This is my fourth post', comments_counter: 0, likes_counter: 0)

first_comment = Comment.create(post: first_post, author: first_user, text: 'first comment' )
second_comment = Comment.create(post: first_post, author: first_user, text: 'second comment' )
third_comment = Comment.create(post: first_post, author: first_user, text: 'third comment' )
fourth_comment = Comment.create(post: first_post, author: first_user, text: 'fourth comment' )
fifth_comment = Comment.create(post: first_post, author: first_user, text: 'fifth comment' )
sixth_comment = Comment.create(post: first_post, author: first_user, text: 'sixth comment' )

Like.create(post: first_post, author: first_user)
Like.create(post: first_post, author: first_user)

first_user.recent_three_posts
first_post.recent_five_comments
```
***
Thank you for taking the time to review this pull request.

### CODE REVIEW

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Olivier,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- Views renders correctly

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider:**
- I think you should change the header title _Authors_ to _Author_, as this project is worked on by an individual contributor. 
Implementing the above change(s) will make your ReadMe appear more professional.
<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by RWUBAKWANAYO** [comment]
## Hi @rloterh,
I appreciate the feedback you provided on this PR. It's more professional.
I would like to ask for more details about optional changes you mentioned, as I noticed that in the README file the title `Author` seem to be `Authors`. 
Thank you once more for your time. I'm looking forward to hearing your suggestions.

**Comment by rloterh** [comment]
Hello @RWUBAKWANAYO 

Thanks for pointing this out. I mean to say you should change from _Authors_ to _Author_, I apologize for the same.

Cheers!

**Comment by RWUBAKWANAYO** [comment]
Okay, Thank you so much @rloterh

**Pull request merged**
